/**
 * Справочники демо-генератора. Все компании, люди и номера — вымышленные.
 */
import type { BodyType, CargoType, VehicleType } from "@/generated/prisma/enums";

export type City = { name: string; country: string; lat: number; lng: number; tz: string; region?: string };

export const CITIES: Record<string, City> = {
  Алматы: { name: "Алматы", country: "KZ", lat: 43.238, lng: 76.945, tz: "Asia/Almaty" },
  Астана: { name: "Астана", country: "KZ", lat: 51.169, lng: 71.449, tz: "Asia/Almaty" },
  Шымкент: { name: "Шымкент", country: "KZ", lat: 42.341, lng: 69.59, tz: "Asia/Almaty" },
  Караганда: { name: "Караганда", country: "KZ", lat: 49.806, lng: 73.085, tz: "Asia/Almaty" },
  Актобе: { name: "Актобе", country: "KZ", lat: 50.283, lng: 57.167, tz: "Asia/Aqtobe" },
  Костанай: { name: "Костанай", country: "KZ", lat: 53.214, lng: 63.624, tz: "Asia/Qostanay" },
  Павлодар: { name: "Павлодар", country: "KZ", lat: 52.287, lng: 76.967, tz: "Asia/Almaty" },
  Бишкек: { name: "Бишкек", country: "KG", lat: 42.874, lng: 74.57, tz: "Asia/Bishkek" },
  Ташкент: { name: "Ташкент", country: "UZ", lat: 41.299, lng: 69.24, tz: "Asia/Tashkent" },
  Самарканд: { name: "Самарканд", country: "UZ", lat: 39.654, lng: 66.959, tz: "Asia/Samarkand" },
  Урумчи: { name: "Урумчи", country: "CN", lat: 43.825, lng: 87.617, tz: "Asia/Shanghai" },
  Москва: { name: "Москва", country: "RU", lat: 55.756, lng: 37.617, tz: "Europe/Moscow" },
  Екатеринбург: { name: "Екатеринбург", country: "RU", lat: 56.838, lng: 60.597, tz: "Asia/Yekaterinburg" },
  Новосибирск: { name: "Новосибирск", country: "RU", lat: 55.008, lng: 82.935, tz: "Asia/Novosibirsk" },
  Челябинск: { name: "Челябинск", country: "RU", lat: 55.16, lng: 61.402, tz: "Asia/Yekaterinburg" },
  Омск: { name: "Омск", country: "RU", lat: 54.989, lng: 73.368, tz: "Asia/Omsk" },
  Стамбул: { name: "Стамбул", country: "TR", lat: 41.008, lng: 28.978, tz: "Europe/Istanbul" },
};

/** Пункты пропуска (точка BORDER маршрута) по паре стран. */
export const BORDERS: Record<string, City> = {
  "KG-KZ": { name: "Кордай", country: "KZ", lat: 43.033, lng: 74.71, tz: "Asia/Almaty" },
  "KZ-UZ": { name: "Жибек Жолы", country: "KZ", lat: 41.335, lng: 69.36, tz: "Asia/Almaty" },
  "CN-KZ": { name: "Хоргос", country: "KZ", lat: 44.21, lng: 80.38, tz: "Asia/Almaty" },
  "KZ-RU": { name: "Кайрак", country: "KZ", lat: 54.1, lng: 62.3, tz: "Asia/Qostanay" },
  "KZ-TR": { name: "Жибек Жолы", country: "KZ", lat: 41.335, lng: 69.36, tz: "Asia/Almaty" },
};

export const ROUTES: [string, string][] = [
  ["Алматы", "Бишкек"],
  ["Алматы", "Ташкент"],
  ["Астана", "Москва"],
  ["Шымкент", "Ташкент"],
  ["Алматы", "Урумчи"],
  ["Урумчи", "Алматы"],
  ["Астана", "Екатеринбург"],
  ["Алматы", "Стамбул"],
  ["Шымкент", "Бишкек"],
  ["Алматы", "Астана"],
  ["Караганда", "Алматы"],
  ["Костанай", "Челябинск"],
  ["Актобе", "Москва"],
  ["Павлодар", "Новосибирск"],
  ["Алматы", "Шымкент"],
  ["Ташкент", "Алматы"],
  ["Бишкек", "Астана"],
  ["Астана", "Омск"],
  ["Самарканд", "Алматы"],
  ["Алматы", "Екатеринбург"],
  ["Урумчи", "Астана"],
];

export type CargoProfile = {
  title: string;
  cargoType: CargoType;
  bodyType: BodyType;
  vehicleType: VehicleType;
  weight: [number, number];
  volume: [number, number];
  packageType: string;
  temperature?: [number, number];
  ratePerKm: number;
};

export const CARGO: CargoProfile[] = [
  {
    title: "Продукты питания: молочная продукция",
    cargoType: "FOOD",
    bodyType: "REFRIGERATOR",
    vehicleType: "TRACTOR_TRAILER",
    weight: [8000, 20000],
    volume: [40, 82],
    packageType: "Паллеты EUR",
    temperature: [2, 6],
    ratePerKm: 1.55,
  },
  {
    title: "Замороженные овощи",
    cargoType: "FOOD",
    bodyType: "REFRIGERATOR",
    vehicleType: "TRACTOR_TRAILER",
    weight: [12000, 21000],
    volume: [50, 82],
    packageType: "Коробки на паллетах",
    temperature: [-18, -15],
    ratePerKm: 1.65,
  },
  {
    title: "Кондитерские изделия",
    cargoType: "FOOD",
    bodyType: "ISOTHERMAL",
    vehicleType: "TRACTOR_TRAILER",
    weight: [6000, 15000],
    volume: [40, 80],
    packageType: "Короба",
    ratePerKm: 1.35,
  },
  {
    title: "Строительные материалы: гипсокартон",
    cargoType: "GENERAL",
    bodyType: "CURTAINSIDER",
    vehicleType: "TRACTOR_TRAILER",
    weight: [15000, 22000],
    volume: [40, 70],
    packageType: "Пачки",
    ratePerKm: 1.2,
  },
  {
    title: "Металлопрокат",
    cargoType: "GENERAL",
    bodyType: "FLATBED",
    vehicleType: "TRACTOR_TRAILER",
    weight: [18000, 24000],
    volume: [20, 40],
    packageType: "Связки",
    ratePerKm: 1.3,
  },
  {
    title: "Бытовая техника",
    cargoType: "ELECTRONICS",
    bodyType: "CURTAINSIDER",
    vehicleType: "TRACTOR_TRAILER",
    weight: [5000, 14000],
    volume: [60, 86],
    packageType: "Коробки на паллетах",
    ratePerKm: 1.3,
  },
  {
    title: "Электроника: ноутбуки и комплектующие",
    cargoType: "ELECTRONICS",
    bodyType: "BOX",
    vehicleType: "TRUCK",
    weight: [1500, 6000],
    volume: [15, 40],
    packageType: "Коробки",
    ratePerKm: 1.45,
  },
  {
    title: "Одежда и обувь",
    cargoType: "CLOTHING",
    bodyType: "CURTAINSIDER",
    vehicleType: "TRACTOR_TRAILER",
    weight: [4000, 10000],
    volume: [60, 86],
    packageType: "Мешки и коробки",
    ratePerKm: 1.25,
  },
  {
    title: "Мебель в упаковке",
    cargoType: "GENERAL",
    bodyType: "CURTAINSIDER",
    vehicleType: "TRACTOR_TRAILER",
    weight: [5000, 12000],
    volume: [70, 90],
    packageType: "Упаковки",
    ratePerKm: 1.25,
  },
  {
    title: "Автозапчасти",
    cargoType: "AUTOMOTIVE",
    bodyType: "CURTAINSIDER",
    vehicleType: "TRACTOR_TRAILER",
    weight: [6000, 16000],
    volume: [30, 70],
    packageType: "Ящики на паллетах",
    ratePerKm: 1.3,
  },
  {
    title: "Промышленное оборудование: компрессорная станция",
    cargoType: "EQUIPMENT",
    bodyType: "LOWBED",
    vehicleType: "TRACTOR_TRAILER",
    weight: [24000, 38000],
    volume: [40, 70],
    packageType: "Без упаковки, крепление",
    ratePerKm: 2.1,
  },
  {
    title: "Станки и оборудование",
    cargoType: "EQUIPMENT",
    bodyType: "CURTAINSIDER",
    vehicleType: "TRACTOR_TRAILER",
    weight: [10000, 20000],
    volume: [30, 60],
    packageType: "Деревянные ящики",
    ratePerKm: 1.45,
  },
  {
    title: "Сельхозпродукция: зерно в биг-бэгах",
    cargoType: "FOOD",
    bodyType: "CURTAINSIDER",
    vehicleType: "TRACTOR_TRAILER",
    weight: [18000, 22000],
    volume: [40, 60],
    packageType: "Биг-бэги",
    ratePerKm: 1.1,
  },
  {
    title: "Фрукты и овощи свежие",
    cargoType: "FOOD",
    bodyType: "REFRIGERATOR",
    vehicleType: "TRACTOR_TRAILER",
    weight: [10000, 20000],
    volume: [50, 82],
    packageType: "Ящики",
    temperature: [4, 8],
    ratePerKm: 1.55,
  },
  {
    title: "Упаковочные материалы: гофрокартон",
    cargoType: "GENERAL",
    bodyType: "CURTAINSIDER",
    vehicleType: "TRACTOR_TRAILER",
    weight: [4000, 9000],
    volume: [70, 90],
    packageType: "Паллеты",
    ratePerKm: 1.15,
  },
  {
    title: "Товары народного потребления",
    cargoType: "GENERAL",
    bodyType: "CONTAINER",
    vehicleType: "TRACTOR_TRAILER",
    weight: [8000, 18000],
    volume: [50, 67],
    packageType: "Контейнер 40'",
    ratePerKm: 1.35,
  },
  {
    title: "Промышленные товары: кабельная продукция",
    cargoType: "OTHER",
    bodyType: "FLATBED",
    vehicleType: "TRACTOR_TRAILER",
    weight: [12000, 20000],
    volume: [25, 50],
    packageType: "Барабаны",
    ratePerKm: 1.3,
  },
  {
    title: "Бытовая химия (безопасная)",
    cargoType: "GENERAL",
    bodyType: "CURTAINSIDER",
    vehicleType: "TRACTOR_TRAILER",
    weight: [8000, 16000],
    volume: [50, 80],
    packageType: "Паллеты",
    ratePerKm: 1.25,
  },
];

const CLIENT_PREFIX = [
  "Astana",
  "Altyn",
  "Steppe",
  "Nomad",
  "Silk Road",
  "Eurasia",
  "Caspian",
  "Tengri",
  "Saryarka",
  "Zhetysu",
  "Irtysh",
  "Tian Shan",
  "Aral",
  "Baiterek",
  "Kok-Tobe",
  "Medeu",
  "Ili",
  "Turan",
  "Khan Tengri",
  "Ulytau",
];
const CLIENT_SUFFIX = [
  "Trade",
  "Distribution",
  "Industrial",
  "Market",
  "Supply",
  "Agro",
  "Build",
  "Foods",
  "Textile",
  "Retail",
  "Motors",
  "Pack",
  "Home",
  "Electro",
  "Group",
];

/** 40 вымышленных клиентов: «Префикс Суффикс» без повторов, в детерминированном порядке. */
export function clientNames(pick: (n: number) => number, count = 40): string[] {
  const names = new Set<string>([
    "Astana Trade",
    "Central Asia Distribution",
    "Steppe Logistics Supply",
    "Nomad Industrial",
    "Silk Road Market",
    "Eurasia Supply",
  ]);
  while (names.size < count) {
    names.add(`${CLIENT_PREFIX[pick(CLIENT_PREFIX.length)]} ${CLIENT_SUFFIX[pick(CLIENT_SUFFIX.length)]}`);
  }
  return [...names];
}

export const CARRIER_NAMES = [
  "Altyn Jol Logistics",
  "Kazakh Express Cargo",
  "Steppe Wheels",
  "Caspian Freight",
  "Tengri Trans",
  "Saryarka Haulage",
  "Zhetysu Transit",
  "Irtysh Line",
  "Nomad Road Carriers",
  "Turan Trucking",
  "Medeu Motors Logistics",
  "Ulytau Cargo Lines",
  "Baiterek Transport",
  "Eurasia Roadways",
  "Aral Fleet",
  "Khan Tengri Haul",
];

export const FIRST_NAMES = [
  "Арман",
  "Данияр",
  "Ерлан",
  "Нурлан",
  "Тимур",
  "Руслан",
  "Азамат",
  "Санжар",
  "Бекзат",
  "Максим",
  "Сергей",
  "Олжас",
  "Ильяс",
  "Кайрат",
  "Марат",
  "Дмитрий",
  "Алихан",
  "Айдос",
  "Ринат",
  "Жандос",
];
export const LAST_NAMES = [
  "Сейткали",
  "Ахметов",
  "Бекенов",
  "Жумабаев",
  "Касымов",
  "Нурпеисов",
  "Оспанов",
  "Тлеубаев",
  "Иванов",
  "Ким",
  "Абдрахманов",
  "Есенов",
  "Мусин",
  "Сагинтаев",
  "Утегенов",
  "Байжанов",
  "Каримов",
  "Садыков",
  "Петренко",
  "Исмаилов",
];
export const OFFICE_NAMES = ["Алия", "Динара", "Айгерим", "Мадина", "Сауле", "Жанна", "Асель", "Гульнара", "Карина", "Ольга"];

export const VEHICLES: { make: string; model: string; body: BodyType; type: VehicleType; capacityKg: number; volumeM3: number }[] = [
  { make: "DAF", model: "XF 480", body: "CURTAINSIDER", type: "TRACTOR_TRAILER", capacityKg: 22000, volumeM3: 86 },
  { make: "VOLVO", model: "FH 500", body: "REFRIGERATOR", type: "TRACTOR_TRAILER", capacityKg: 21000, volumeM3: 82 },
  { make: "SCANIA", model: "R 450", body: "CURTAINSIDER", type: "TRACTOR_TRAILER", capacityKg: 22000, volumeM3: 86 },
  { make: "MAN", model: "TGX 18.510", body: "ISOTHERMAL", type: "TRACTOR_TRAILER", capacityKg: 20000, volumeM3: 82 },
  { make: "MERCEDES-BENZ", model: "ACTROS 1845", body: "CONTAINER", type: "TRACTOR_TRAILER", capacityKg: 26000, volumeM3: 67 },
  { make: "RENAULT", model: "T 480", body: "CURTAINSIDER", type: "TRACTOR_TRAILER", capacityKg: 22000, volumeM3: 86 },
  { make: "KAMAZ", model: "54901", body: "FLATBED", type: "TRACTOR_TRAILER", capacityKg: 25000, volumeM3: 45 },
  { make: "VOLVO", model: "FH 460", body: "REFRIGERATOR", type: "TRACTOR_TRAILER", capacityKg: 21000, volumeM3: 82 },
  { make: "SCANIA", model: "S 500", body: "LOWBED", type: "TRACTOR_TRAILER", capacityKg: 40000, volumeM3: 70 },
  { make: "ISUZU", model: "FVR 34", body: "BOX", type: "TRUCK", capacityKg: 8000, volumeM3: 40 },
];
